# Generated by Django 5.1.7 on 2025-03-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
