# Generated by Django 5.1.7 on 2025-03-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_name', models.CharField(max_length=100, unique=True, verbose_name='API密钥名称')),
                ('api_key', models.CharField(help_text='OpenAI API密钥，请妥善保管', max_length=255, verbose_name='API密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': 'OpenAI API设置',
                'verbose_name_plural': 'OpenAI API设置',
                'ordering': ['-last_updated'],
            },
        ),
    ]
