# Generated by Django 5.1.7 on 2025-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20250318_1500'),
    ]

    operations = [
        # 添加choice_number字段
        migrations.AddField(
            model_name='choice',
            name='choice_number',
            field=models.PositiveIntegerField(default=1, help_text='Option number (1-4)', verbose_name='Choice Number'),
        ),
        # 设置唯一约束
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'choice_number')},
        ),
    ]
