# Generated by Django 5.1.7 on 2025-03-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20250318_1503'),
    ]

    operations = [
        migrations.RunSQL(
            # 使用SQL操作移除passing_score字段（如果存在）
            "PRAGMA foreign_keys=off; "
            "CREATE TABLE quizzes_quiz_new ("
            "id INTEGER PRIMARY KEY AUTOINCREMENT, "
            "title VARCHAR(200) NOT NULL, "
            "description TEXT NOT NULL, "
            "time_limit INTEGER UNSIGNED NOT NULL, "
            "is_published BOOL NOT NULL, "
            "created_at DATETIME NOT NULL, "
            "updated_at DATETIME NOT NULL, "
            "course_id INTEGER NOT NULL REFERENCES courses_course (id) DEFERRABLE INITIALLY DEFERRED, "
            "end_time DATETIME NULL, "
            "start_time DATETIME NULL); "
            "INSERT INTO quizzes_quiz_new SELECT id, title, description, time_limit, "
            "is_published, created_at, updated_at, course_id, end_time, start_time FROM quizzes_quiz; "
            "DROP TABLE quizzes_quiz; "
            "ALTER TABLE quizzes_quiz_new RENAME TO quizzes_quiz; "
            "PRAGMA foreign_keys=on;",
            # 回滚操作为空，因为我们不能轻易恢复删除的列
            ""
        ),
    ]
